### ISSUE TITLE
Git jump --last or git jump -l

### ISSUE THREAD

**Issue by AdamHess** [mykolaharmash/git-jump#8]
makes it easy to go back to the last branch you just switched from 

`git jump --last` 

or 

`git jump -l`

would let you switch to the last branch you were just on so that you can easily go back and forth between current and previous one. 

not really a critical feature, but a real nice to have

**Comment by mykolaharmash** [comment]
Hey 👋 Thank you for bringing this up! I think this case might be covered already in a bit different way.

You can provide `-` as an argument to the native, like this `git switch -`, this will switch you to the previous branch. And because `git jump` under the hood translates into `git switch` commands and supports all its options, you can do `git jump -`.

Let me know if this covers your usecase or maybe I missed something.

**Comment by AdamHess** [comment]
I learn something new about git every day (switch is a 'relatively' new
feature.) thanks!

**Comment by mykolaharmash** [comment]
Awesome! I'll close this one for now, but feel free to re-open if you think something is missing 🙌
